import { Vehicle } from "./vehicle";

export type InitalResponse<T> = {
  success: boolean;
  message: string;
  data: T;
};

export type BaseQueryParams = {
  q?: string | null;
  page?: number | null;
  limit?: number | null;
  i?: string | null;
};

export enum SystemRole {
  ADMIN = "admin",
  DEALER = "dealer",
  EMPLOYEE = "employee",
  USER = "user",
}

export type DealerResale = {
  saleId: string;
  transNo: string | null;
  registrationNo: string;
  chessisId: string;
  engineId: string;
  prevCusCode: string;
  newCusCode: string;
  saleDate: string;
  remarks: string | null;
  comCode: string;
  makeUid: string;
  makeDate: string;
  mdyUid: string | null;
  mdyDate: string | null;
  recycledUid: string | null;
  recycledDate: string | null;
  recycledFlag: "Y" | "N";
  newCus?: {
    cusName: string;
    tmNo1: string;
    panNo: string;
    pofficeAddress: string;
  };
  vehicle: {
    modelNo: string;
    color: string;
  };
};

export type DealerResaleResponse = InitalResponse<{
  list: DealerResale[];
  count: number;
}>;

export type Customer = {
  cusCode: string;
  cusName: string;
  cusDescription: string | null;
  cusId: string | null;
  groupCusId: string | null;
  motherCusCode: string;
  grandCusCode: string;
  pofficeAddress: string | null;
  tofficeAddress: string | null;
  tmNo1: string | null;
  tmNo2: string | null;
  tmNo3: string | null;
  faxNo: string | null;
  emailId: string | null;
  agentCode: string | null;
  empCode: string | null;
  cusType: string;
  slCode: string;
  panNo: string | null;
  exciseNo: string | null;
  gstNo: string | null;
  crLimitAmt: number | null;
  crDays: number | null;
  crActFlag: string | null;
  cPercent: number | null;
  orderLimitQty: number | null;
  dueBillCount: number | null;
  bgAmt: number;
  priorCrLimitAmt: number | null;
  statusId: string | null;
  termsCond: string | null;
  acCode: string;
  prCode: string | null;
  overDueFlag: string;
  authorizedFlag: string;
  bgExpiryDate: string | null;
  exLimitPercent: number | null;
  maxSalesValue: number | null;
  cashCusFlag: string | null;
  gstartNo: string | null;
  pfixTxt: string | null;
  interestRate: number | null;
  openingDate: string | null;
  maturityDate: string | null;
  countryId: string | null;
  zoneId: string | null;
  districtId: string | null;
  cityId: string | null;
  mrPerson: string | null;
  regionId: string | null;
  transLockFlag: string | null;
  overdueFlag: string;
  gskuFlag: string;
  remarks: string | null;
  comCode: string;
  braCode: string;
  makeUid: string;
  makeDate: string;
  mdyUid: string | null;
  mdyDate: string | null;
  wFlag: string | null;
  synId: string | null;
  recycledUid: string | null;
  recycledDate: string | null;
  recycledFlag: string;
  tdsId: string | null;
  odcAmount: number;
  reconcileFlag: string;
  reconcileDate: string | null;
  adCode: string | null;
  iecNo: string | null;
  fssaiNo: string | null;
  panNoType: string;
  pdcChqAmt: number | null;
  optBraCode: string | null;
  areaId: string | null;
  supervisorCode: string | null;
  unitHeadCode: string | null;
  remarks2nd: string | null;
  remarks3rd: string | null;
  confirmationDate: string | null;
  reconcileUid: string | null;
  tinNo: string | null;
  crLog: string | null;
  blackListFlag: string;
  dueAmount: number | null;
  dueAmountCheckedTime: string | null;
  eximCode: string | null;
};

export type CustomerResponse = InitalResponse<{
  customers: Customer[];
  count: number;
}>;

export type JobCard = {
  jobId: string;
  jobNo: number;
  jobDate: string;
  chasisNumber: string;
  engineNumber: string;
  empCode: string;
  registrationNumber: string;
  appointmentTypeId: string;
  jobTypeId: string;
  cusCode: string;
  vehicleArrivalDate: string;
  jobAckFlag: "Y" | "N";
  jobAckSmsFlag: "Y" | "N";
  jobCompleteBy: string | null;
  jobCompleteDate: string | null;
  jobCompleteSmsFlag: "Y" | "N";
  currentKm: number | "";
  days: number | null;
  vehicleDeliveryDate: string | null;
  comCode: string;
  braCode: string;
  makeDate: string;
  makeUid: string;
  mdyDate: string | null;
  mdyUid: string | null;
  recycledDate: string | null;
  recycledUid: string | null;
  recycledFlag: "Y" | "N";
  vehicle: {
    transNo: string;
    refNo: string;
    srNo: number;
    itCode: string;
    batchNo: string;
    mfgDate: string | null;
    expiryDate: string | null;
    mrpPrice: number | null;
    unit: string;
    quantity: number;
    rate: number | null;
    remarks: string | null;
    transTypeFlag: string | null;
    pfixTxt: string | null;
    sfixTxt: string | null;
    fromSrNo: string | null;
    toSrNo: string | null;
    itSrNo: string;
    trackType: string | null;
    sessionId: string | null;
    itModelNo: string | null;
    netWeight: number | null;
    grossWeight: number | null;
    avgWt: number | null;
    meter: number | null;
    btSrTransFlag: string | null;
    itSrTransFlag: string | null;
    lineItFreeQty: number | null;
    itGsm: number | null;
    batchSize: number | null;
    brustFactor: number | null;
    vendorCode: string | null;
    refVNo: string | null;
    nonStockFlag: "Y" | "N";
    engineeId: string;
    chessisId: string;
    registrationId: string | null;
    batteryId: string | null;
    mfgYear: string;
    syncId: string | null;
    machineNo: string | null;
    docCode: string;
    comCode: string;
    braCode: string;
    makeUid: string;
    makeDate: string;
    mdyDate: string | null;
    mdyUid: string | null;
    recycledUid: string | null;
    recycledDate: string | null;
    recycledFlag: "Y" | "N";
    registrationNo: string;
    locCode: string;
    quantity2nd: number | null;
    quantity3nd: number | null;
    coilNo: string | null;
    gsmId: string | null;
    colorId: number;
    brandId: string | null;
    fabType: string | null;
    itSizeId: string | null;
    freeQty: number | null;
    cusCode: string;
    vDate: string | null;
    modelNo: string;
    color: {
      colorId: number;
      colorName: string;
      comCode: string;
      remarks: string | null;
      makeUid: string;
      makeDate: string;
      recycledUid: string | null;
      recycledDate: string | null;
      recycledFlag: "Y" | "N";
      mdyDate: string | null;
      mdyUid: string | null;
    };
  };
  customer: {
    cusCode: string;
    cusName: string;
    cusDescription: string | null;
    cusId: string | null;
    groupCusId: string;
    motherCusCode: string;
    grandCusCode: string;
    pofficeAddress: string;
    tofficeAddress: string | null;
    tmNo1: string;
    tmNo2: string | null;
    tmNo3: string | null;
    faxNo: string | null;
    emailId: string | null;
    agentCode: string | null;
    empCode: string | null;
    cusType: string | null;
    slCode: string;
    panNo: string;
    exciseNo: string | null;
    gstNo: string | null;
    crLimitAmt: number | null;
    crDays: number | null;
    crActFlag: string | null;
    cPercent: number | null;
    orderLimitQty: number | null;
    dueBillCount: number | null;
    bgAmt: number | null;
    priorCrLimitAmt: number | null;
    statusId: string | null;
    termsCond: string | null;
    acCode: string | null;
    prCode: string | null;
    overDueFlag: "Y" | "N";
    authorizedFlag: string | null;
    bgExpiryDate: string | null;
    exLimitPercent: number | null;
    maxSalesValue: number | null;
    cashCusFlag: string | null;
    gstartNo: string | null;
    pfixTxt: string | null;
    interestRate: number | null;
    openingDate: string | null;
    maturityDate: string | null;
    countryId: string | null;
    zoneId: string | null;
    districtId: string | null;
    cityId: string | null;
    mrPerson: string | null;
    regionId: string | null;
    transLockFlag: string | null;
    overdueFlag: "Y" | "N";
    gskuFlag: string;
    remarks: string | null;
    comCode: string;
    braCode: string | null;
    makeUid: string;
    makeDate: string;
    mdyUid: string | null;
    mdyDate: string | null;
    wFlag: string | null;
    synId: string | null;
    recycledUid: string | null;
    recycledDate: string | null;
    recycledFlag: "Y" | "N" | null;
    tdsId: string | null;
    odcAmount: number | null;
    reconcileFlag: "Y" | "N";
    reconcileDate: string | null;
    adCode: string | null;
    iecNo: string | null;
    fssaiNo: string | null;
    panNoType: string;
    pdcChqAmt: number | null;
    optBraCode: string | null;
    areaId: string | null;
    supervisorCode: string | null;
    unitHeadCode: string | null;
    remarks2nd: string | null;
    remarks3rd: string | null;
    confirmationDate: string | null;
    reconcileUid: string | null;
    tinNo: string | null;
    crLog: string | null;
    blackListFlag: "Y" | "N";
    dueAmount: number | null;
    dueAmountCheckedTime: string | null;
    eximCode: string | null;
  };
  complaints: {
    jobComplaintId: string;
    complaintCode: string;
    jobId: string;
    empCode?: string | null;
    assignDate?: string | null;
    complaintDescription: string;
    employee: {
      empCode: string;
      empName: string;
    };
    complaintMaster: {
      complaintCode: string;
      complaintName: string;
      rate: number;
      complaintTypeId: number;
      complaintTypeMaster: {
        complaintTypeId: number;
        complaintTypeName: string;
        description: string;
      };
    };
  }[];
};

export type JobCardResponse = InitalResponse<{
  jobs: JobCard[];
  count: number;
}>;
export type CustomerVehicleResponse = InitalResponse<{
  vehicles: Vehicle[];
  count: number;
}>;
